### PR TITLE
feat: add "replace" functionality.

### PR DESCRIPTION
**Pull request by pselden**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the new behavior (if this is a feature change)?**
Adds support for transaction replacements as outlined in: https://github.com/stellar/stellar-protocol/pull/441/

Adds 4 methods to StellarUri base class:
1. addReplacement - adds a single replacement
2. setReplacements - completely replaces the replacements list
3. getReplacements - gets a list of replacements
4. removeReplacement - removes one or more replacements corresponding to the given id

The `Replacement[]` returned is of this form:
```ts
{
  id: string; // the identifier for the given replacement
  path: string; // the path in the transaction to replace
  hint: string; // the hint for the replacement
}
```

* **Other information**:

This currently does not handle actually performing the replacement.

CC: @andywer @pitsevich -- would you mind giving me some feedback about the API surface for this? I decided to potentially duplicate the hints if there are multiple replacements for a single id because I wanted to make it simple for the base case where you just have a single replacement.

### CODE REVIEW

**Comment by andywer** [comment]
Hey Paul! Thanks for asking us :)

Are planning to do the replacement in this package, though? I think two methods `getReplacements()` and `applyReplacements({ key: "value" })` would make a lot of sense.

A little note not to merge this before the README has been updated always helps me a lot. But obviously your call ;)

One last thought: Might be good not to mutate the `StellarUri` instance, but return a new one, since it might have unintended side effects on other code that already has a reference.

**Comment by pselden** [comment]
https://github.com/stellarguard/stellar-uri/pull/10#issuecomment-550543942 thanks for the feedback. I'll definitely have wait to merge it until I have a readme/demo for it.

I'm actually going to wait even a little bit longer to see if there are any changes to the delimiters or additional guidance from @nikhilsaraf. 

So you think doing the actual replacements in this library would be useful? I was thinking it wouldn't make a lot of sense since you'd be operating on the transaction itself and not the URI, but given that this is the maybe the only place replacements will be used, it probably does. If it's useful in a more generic sense i could split it into another library.

Unfortunately a generic replacement library for txrep seems pretty large (see https://github.com/xdrpp/stc for the reference implementation)...

**Comment by andywer** [comment]
> Unfortunately a generic replacement library for txrep seems pretty large

Yeah, that is an issue. If the actual replacement was to happen in a separate library, one could mitigate that issue to some degree (like lazy-loading the replacement lib). The overall size issue would still persist, though, especially since now even the basic source account replacement has to be done via txrep.

We should definitely talk to @nikhilsaraf once more. We need some way to do at least the most common and basic replacements without a full txrep implementation that inflates the bundle.

**Comment by pselden** [comment]
I've started implementing txrep here: https://github.com/stellarguard/txrep/tree/initial-commit

It's more work than I was hoping but there's an end in sight.

**Comment by pitsevich** [comment]
Probably would be a good idea to have a simple replacement included in the library (e.g. source account, but good to see the getReplacements() method - that would be helpful, I'm sure we'd use that!

**Comment by nikhilsaraf** [comment]
I agree that the library should support the basic replacement of `sourceAccount` out-of-the-box. More complex replacements can be handled in a separate library.

@pitsevich and I spoke at Meridian and we agreed that SEP-0007 should initially support only `sourceAccount` replacements and wait for further development of libraries to support more complex replacements. I will update the spec to reflect this along with other suggested changes such as delimiters (once finalized) so it's easier for wallet developers to implement this new capability in SEP-0007.

**Comment by nikhilsaraf** [comment]
@pseldon see this sample code to get the tx rep field from a given XDR: https://xdrpp.github.io/stc/pkg/github.com/xdrpp/stc/stcdetail/index.html#GetTxrepField

**Comment by pselden** [comment]
https://github.com/stellarguard/stellar-uri/pull/10#issuecomment-558070331 -- unfortunately most of the implementation of that is deferred to the xdrgo base library -- and the equivalent js library of js-xdr names things differently so it cannot be used in the same automatic manner. I just have been manually implementing each operation type to go to-from... I'm almost done!

Btw I raised https://github.com/stellar/stellar-protocol/issues/461 to talk about the difficulty there. Unfortunately seems like it will need some changes in js-xdr for it to be as easy to convert as the go library.

**Comment by pselden** [comment]
https://github.com/stellarguard/stellar-uri/pull/10#issuecomment-558063459 -- sounds good. I'm close enough that I can probably implement all replacements, but agreed for initial adoption it's best to simplify.

I'll likely add a few helper methods for checking whether the source account needs to be replaced, and doing that replacement.

Maybe: 

`needsSourceAccountReplacement(): boolean`

and 

`replaceSourceAccount(accountId: string, sequenceNumber?: string)`

**Comment by pselden** [comment]
Took longer than I wanted, but I got https://github.com/stellarguard/txrep - Demo: https://stellarguard.github.io/txrep/demo/ working.

I'll do the integration here next.

**Comment by pselden** [comment]
I'm back working on this but I think it'll take a few tries to get a proper API for this, so I'll probably release a beta version first.

**Comment by pselden** [comment]
Hmm I kind of like how this turned out so maybe I won't need a pre-release, or any helper methods, but I'd definitely like your feedback @pitsevich and @andywer.

Take a look at how it functions in the README examples here: https://github.com/stellarguard/stellar-uri/tree/replacements#replacements

Or the tests: https://github.com/stellarguard/stellar-uri/pull/10/files#diff-36649a0afcb26b6f947b78a893721dbfR60

**Comment by andywer** [comment]
Hey Paul!

I just had a quick look. Looks good, just one remark about applying replacements. Right now the API is used like this:

```ts
const newUri = uri.replace(
  { id: 'SEQ', value: '10' }
  // ...
);
```

It seems a bit weird that the method accepts a variable number of parameters instead of an array of replacement values – this will also prevent adding an addition replacement options parameter later if need be.

Also I wonder if there is any real chance of the `replace` method taking something else than a key and a value per replacement.

This would seem like a more intuitive and concise way to call `replace`:

```ts
const newUri = uri.replace({
  SEQ: 10
});
```

What do you think?

**Comment by pselden** [comment]
https://github.com/stellarguard/stellar-uri/pull/10#issuecomment-570888349 That's a great idea. I've implemented it now.

**Comment by pselden** [comment]
I published 1.1.0 with this functionality. Please let me know if anyone ends up using it an encounters any problems.

I updated the demo to include replace fields in the tx URI: https://stellarguard.github.io/stellar-uri/demo/

**Comment by andywer** [comment]
Good stuff! 👍

**Pull request merged**
